import sys     
import os
os.system(f"{sys.executable} -m pip install biopython matplotlib")

class TreeNode:
    def __init__(self,name,left=None,right=None,distance=0.0):   
        self.name=name          #节点名称
        self.left=left          #左孩子
        self.right=right        #右孩子
        self.distance=distance  #节点高度
    
    def is_leaf(self):
        return self.left is None and self.right is None
    
    def to_newick(self):
        if self.is_leaf():
            return self.name
        else:
            dist_l=self.distance-self.left.distance
            dist_r=self.distance-self.right.distance
            return f'({self.left.to_newick()}:{dist_l:.4f},{self.right.to_newick()}:{dist_r:.4f})'   

def parse_input():
    lines=sys.stdin.read().split()
    
    if not lines: return None,None
    
    N=int(lines[0])             #物种数量
    species_names=lines[1:N+1]  #物种名字
    flat_mat=lines[N+1:]        
    mat=[]                      #遗传距离矩阵
    for _ in range(N):
        row=[float(x) for x in flat_mat[_*N:(_+1)*N]]
        mat.append(row)
    return species_names,mat

def find_min_idx(mat):
    '''在矩阵中寻找非对角线遗传距离的最小值'''
    n,min_val,bi,bj=len(mat),float('inf'),-1,-1

    for i in range(n):
        for j in range(i+1,n):
            if mat[i][j]<min_val:
                min_val,bi,bj=mat[i][j],i,j
    return bi,bj
        
def update(mat,size,i,j):
    '''
    UPGMA:
    1.计算新节点到其他各节点的加权平均值(距离)
    2.移除旧的行i和j
    3.移除旧的列i和j
    4.添加新的行和列
    '''
    n=len(mat)
    #计算新节点到除i,j以外节点的距离
    new_distances=[]
    for k in range(n):
        if k!=i and k!=j:
            dist=(mat[i][k]*size[i]+mat[j][k]*size[j])/(size[i]+size[j])
            new_distances.append(dist)
   
    #构建新矩阵
    new_mat=[]
    remainidxs=[k for k in range(n) if k!=i and k!=j] #非i非j的列表索引
        
    #填充新矩阵的保留部分    
    for row_idx in remainidxs:
        new_row=[]
        for col_idx in remainidxs:
            new_row.append(mat[row_idx][col_idx])
        #在这一行的末尾加上到新节点的距离
        # 找到对应k在new_distances中的位置    
        kdist=remainidxs.index(row_idx)
        new_row.append(new_distances[kdist])
        new_mat.append(new_row)
        
    #添加新的一行(新节点到自己距离为0)    
    last_row=new_distances+[0.0]
    new_mat.append(last_row)

    return new_mat

def visualize_tree(newick_str):
    """
    可视化函数：包含鲁棒性处理。
    如果 Biopython 或环境不兼容，程序将优雅地提示而非崩溃。
    """
    print("\n" + "="*40)
    print("进化树可视化（Phylogenetic Tree Visualization）")
    print("="*40)
    
    try:
        from Bio import Phylo
        import io
        import matplotlib.pyplot as plt
        
        # 将 Newick 字符串转为内存文件对象
        tree_file = io.StringIO(newick_str)
        tree = Phylo.read(tree_file, "newick")
        
        # 绘图设置
        fig = plt.figure(figsize=(10, 6), dpi=100)
        axes = fig.add_subplot(1, 1, 1)
        Phylo.draw(tree, axes=axes, do_show=False)
        plt.title("Phylogenetic Tree generated by UPGMA")
        print("[成功] 绘图窗口已弹出，请查看图片。")
        plt.show()
        
    except ImportError:
        print("[提示] 未检测到 Biopython 或 Matplotlib 库。")
        print("您可以在终端运行 'pip install biopython matplotlib' 来开启图形化预览。")
    except Exception as e:
        print(f"[提示] 图形化渲染失败: {e}")
        print("这可能是由于 Python 版本过新（如 3.14 预览版）导致库不兼容。")
    
    print("\nNewick 标准文本格式 (可复制到 iTOL 等在线工具查看):")
    print(newick_str)

def solve():
    names,mat=parse_input()
    n=len(names)
    nodes=[TreeNode(name) for name in names]
    sizes=[1]*n
    
    #循环合并至只剩一个点
    while len(nodes)>1:
        i,j=find_min_idx(mat)
        half_dist=mat[i][j]/2.0    #最小距离的一半为新节点的高度
        #创建新节点
        new_node=TreeNode( 
            name=f'({nodes[i].name}+{nodes[j].name})',
            left=nodes[i],
            right=nodes[j],
            distance=half_dist
        )
        
        #更新矩阵和列表(先更新mat后更新nodes，更新mat依赖旧的nodes的索引)
        mat=update(mat,sizes,i,j)
        
        #更新sizes
        new_size=sizes[i]+sizes[j]
        remain_sizes=[sizes[k] for k in range(len(sizes)) if k!=i and k!=j]
        sizes=remain_sizes+[new_size]
        
        #更新nodes
        remain_nodes=[nodes[k] for k in range(len(nodes)) if k!=i and k!=j]
        nodes=remain_nodes+[new_node]
    
    print('Newick Format:')
    print(nodes[0].to_newick()+';')
 
    newick_text = nodes[0].to_newick() + ";"
    visualize_tree(newick_text)

if __name__=="__main__":
    solve()

